from selenium import webdriver
from selenium.webdriver.common.by import By
# Initialize the WebDriver (e.g., Chrome)
driver = webdriver.Chrome()

# Open a webpage
driver.get('https://investsage.com/investor/my-investment/list')

my_investments_heading = driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div/main/section/div/div/div/div[1]/div/div/h4')
filter_headings = driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div/main/section/div/div/div/div[2]/h4')
status_text = driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div/main/section/div/div/div/div[2]/div[1]/div[1]/div/label')
status_dropdown = driver.find_element(By.XPATH, '//*[@id="status_filter"]') 
date_range_text= driver.find_element(By.XPATH, '/html/body/div[1]/div[2]/div/main/section/div/div/div/div[2]/div[1]/div[2]/div/label')
date_range_input = driver.find_element(By.XPATH, '//*[@id="date-range"]')
show_entries_text = driver.find_element(By.XPATH, '//*[@id="my_investment_length"]/label')
show_entries_dropdown = driver.find_element(By.XPATH, '//*[@id="my_investment_length"]/label/select')
search_label= driver.find_element(By.XPATH, '//*[@id="my_investment_filter"]/label')
search_input = driver.find_element(By.XPATH, '//*[@id="my_investment_filter"]/label/input')
show_entries_info = driver.find_element(By.XPATH, '//*[@id="my_investment_info"]')
previous_text = driver.find_element(By.XPATH, '//*[@id="my_investment_previous"]')
next_text = driver.find_element(By.XPATH, '//*[@id="my_investment_next"]')
s_no_heading = driver.find_element(By.XPATH, '//*[@id="my_investment"]/thead/tr/th[1]')
batch_code_heading = driver.find_element(By.XPATH, '//*[@id="my_investment"]/thead/tr/th[2]')
item_title_heading = driver.find_element(By.XPATH, '//*[@id="my_investment"]/thead/tr/th[3]')
invested_amount_heading = driver.find_element(By.XPATH, '//*[@id="my_investment"]/thead/tr/th[4]')
batch_status_heading = driver.find_element(By.XPATH, '//*[@id="my_investment"]/thead/tr/th[5]')
invested_at_heading = driver.find_element(By.XPATH, '//*[@id="my_investment"]/thead/tr/th[6]')
action_heading = driver.find_element(By.XPATH, '//*[@id="my_investment"]/thead/tr/th[7]')
s_no_text = driver.find_element(By.XPATH, '//*[@id="my_investment"]/tbody/tr[1]/td[1]')
batch_code_text = driver.find_element(By.XPATH, '//*[@id="my_investment"]/tbody/tr[1]/td[2]')
item_title_text = driver.find_element(By.XPATH, '//*[@id="my_investment"]/tbody/tr[1]/td[3]')
invested_amount_text = driver.find_element(By.XPATH, '//*[@id="my_investment"]/tbody/tr[1]/td[4]')
batch_status_text = driver.find_element(By.XPATH, '//*[@id="my_investment"]/tbody/tr[1]/td[5]/span')
invested_at_text = driver.find_element(By.XPATH, '//*[@id="my_investment"]/tbody/tr[1]/td[6]')
action_button_dropdown = driver.find_element(By.XPATH, '//*[@id="my_investment"]/tbody/tr[1]/td[7]/div/button')
action_button_dropdown_option = driver.find_element(By.XPATH,'//*[@id="my_investment"]/tbody/tr[1]/td[7]/div/div/a')
