from selenium import webdriver
from selenium.webdriver.common.by import By

# Initialize the WebDriver (e.g., Chrome)
driver = webdriver.Chrome()

# Open a webpage
driver.get('https://investsage.com/investor/wallet')

my_wallet_heading = driver.find_element(By.XPATH, "/html/body/div/div[2]/div/main/div/div/div[1]/h4")
account_details_heading = driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[1]/div/div[1]/h4')
account_details_icon= driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[1]/div/div[1]/h4/i')
topup_instructions_heading = driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[2]/div/div[1]/h4')
topup_instructions_icon= driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[2]/div/div[1]/h4/i')
your_reference_code_subheading= driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[1]/div/div[2]/div/div[1]/p[1]/strong')
account_balance_subheading=  driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[1]/div/div[2]/div/div[1]/p[1]/strong')
reference_code = driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[1]/div/div[2]/div/div[1]/h2')
account_balance = driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[1]/div/div[2]/div/div[2]/h2')
reference_code_text = driver.find_element(By.XPATH, '/html/body/div/div[2]/div/main/section/div[1]/div[1]/div/div[2]/div/div[1]/p[2]')
investsage_bank_account_heading = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/h4')
beneficiary_subheading = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[2]/strong')
account_no_subheading= driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[2]/strong')
sort_code_subheading = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[3]/strong')
beneficiary_address_subheading = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[4]/strong')
payment_institution_subheading = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[5]/strong')
payment_institution_address_subheading = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[6]/strong')
note_subheading= driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[7]/strong')
beneficiary= driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[1]')
account_number = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[2]')
sort_code= driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[3]')
beneficiary_address= driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[4]')
payment_institution = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[5]')
payment_institution_address = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/p[6]')
note = driver.find_element(By.XPATH, '//*[@id="top_instruction"]/div/div/h4')
withdraw_button = driver.find_element(By.XPATH,'/html/body/div/div[2]/div/main/div/div/div[2]/a')
transaction_history_heading = driver.find_element(By.XPATH,'/html/body/div/div[2]/div/main/div/div/div[2]/a')
transaction_history_icon = driver.find_element(By.XPATH,'/html/body/div/div[2]/div/main/section/div[2]/div/div/div[1]/h4/i')
search_label = driver.find_element(By.XPATH,'//*[@id="wallet_transaction_history_table_filter"]/label')
search_input = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table_filter"]/label/input')
search_entries_label = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table_length"]/label')
search_entries_dropdown = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table_length"]/label/select')
s_no_heading = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/thead/tr/th[1]')
type_heading = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/thead/tr/th[2]')
batch_code_heading= driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/thead/tr/th[3]')
reference_no_heading =  driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/thead/tr/th[4]')
amount_heading = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/thead/tr/th[5]')
created_date_heading = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/thead/tr/th[6]')
s_no_text = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/tbody/tr[1]/td[1]')
type_text = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/tbody/tr[1]/td[2]')
batch_code_text = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/tbody/tr[1]/td[3]')
reference_no_text = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/tbody/tr[1]/td[4]')
amount_text= driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/tbody/tr[1]/td[5]')
created_date_text =  driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table"]/tbody/tr[1]/td[6]')
previous_text = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table_previous"]')
next_text = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table_next"]')
showing_entries_info_text = driver.find_element(By.XPATH, '//*[@id="wallet_transaction_history_table_info"]')
